### ISSUE TITLE
Docker exits

### ISSUE THREAD

**Issue by Exist2Resist** [NoMore201/playmaker#42]
I launch the Docker and it exits after a couple min with the following in the log.
Started I a server reboot. 

```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/concurrent/futures/process.py", line 232, in _process_worker
r = call_item.fn(*call_item.args, **call_item.kwargs)
File "/usr/local/lib/python3.7/site-packages/playmaker/service.py", line 35, in get_details_from_apk
details['versionCode'] = int(a.version_code)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/bin/pm-server", line 60, in <module>
service.update_state()
File "/usr/local/lib/python3.7/site-packages/playmaker/service.py", line 215, in update_state
app = future.result()
File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 425, in result
return self.__get_result()
File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
raise self._exception
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by Exist2Resist** [comment]
I made some changes to the docker mainly I added the missing docker run variables like time zone, locale, etc. Now I'm getting a new error....

```
Repo already initalized, skipping init
Checking config.py file
Traceback (most recent call last):
File "/usr/local/bin/pm-server", line 36, in <module>
service = Play(debug=args.debug, fdroid=args.fdroid)
File "/usr/local/lib/python3.7/site-packages/playmaker/service.py", line 71, in __init__
self.fdroid_init()
File "/usr/local/lib/python3.7/site-packages/playmaker/service.py", line 109, in fdroid_init
with open('config.py', 'r') as config_file:
PermissionError: [Errno 13] Permission denied: 'config.py'
```
