### ISSUE TITLE
Docker container exits after pull

### ISSUE THREAD

**Issue by Pablare** [NoMore201/playmaker#52]
I'm running a docker container with the following command 
`docker run -d --name playmaker \
    -p 5000:5000 \
    -v /srv/fdroid:/data/fdroid \
    -e HTTPS_CERTFILE="/srv/https.crt" \
    -e HTTPS_KEYFILE="/srv/https.key" \
    -e LANG_LOCALE="en_UK" \
    -e LANG_TIMEZONE="Europe/Berlin" \
    -e DEVICE_CODE="oneplus3" \
    nomore201/playmaker`

but after succesfully pulling it isn't running so I try to start it again and docker start playmaker -i gives

`error initializing fdroid repository CRITICAL: Android SDK path "/opt/android-sdk-linux" does not contain "platform-tools/"!
CRITICAL: Unknown exception found!
Traceback (most recent call last):
  File "/usr/bin/fdroid", line 147, in <module>
    main()
  File "/usr/bin/fdroid", line 124, in main
    mod.main()
  File "/usr/lib/python3/dist-packages/fdroidserver/init.py", line 125, in main
    os.mkdir('repo')
PermissionError: [Errno 13] Permission denied: 'repo'`

**Comment by nilsglow** [comment]
I have the same problem with a newly built image. There just is no `/opt/android-sdk-linux/platform-tools/`.

**Comment by basenc** [comment]
Solved by manually installing and mounting android SDK platform tools
https://dl.google.com/android/repository/platform-tools_r29.0.5-linux.zip

```
volumes: 
  - "./platform-tools:/opt/android-sdk-linux/platform-tools"
```

**Comment by basenc** [comment]
oh, there's already a better solution
https://github.com/NoMore201/playmaker/issues/43#issuecomment-462142646
